import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dsidebar from "./components/Dsidebar";
import Dheader from "./components/Dheader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      
      <body className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-white h-screen overflow-hidden">
        {/* Main Container */}
        <div className="flex h-full bg-slate-950">
          {/* Sidebar */}
          <div className="sidebar-container fixed md:static left-0 top-0 h-screen z-40 md:z-0 w-64">
            <Dsidebar />
          </div>

          {/* Main Content Area */}
          <div className="main-content flex-1 flex flex-col overflow-hidden md:ml-0 h-screen">
            {/* Header */}
            <div className="header-container sticky top-0 z-30 bg-gradient-to-r from-slate-900/95 to-slate-800/95 backdrop-blur-xl border-b border-slate-700/50 flex-shrink-0">
              <Dheader />
            </div>

            {/* Content */}
            <div className="content-wrapper flex-1 overflow-y-auto">
              <div className="content-inner p-6 lg:p-8">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
